### ISSUE TITLE
Make barren land per land type text bigger/more readable on construction page

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#98]
![image](https://user-images.githubusercontent.com/1611537/31390574-8d7a074e-add4-11e7-8a28-5511f4c54085.png)

Currently it's quite small, but it's important to know how many acres of barren land you have.

**Comment by straube** [comment]
Do you have something in mind for this one?

**Comment by WaveHack** [comment]
Not in particular. I'm bad with UI and UX design. But it's an important metric to look at when constructing buildings, since you're limited by the amount of barren land you have.

Feel free to just make it bigger, or refactor it into something creative! 😃

**Comment by straube** [comment]
I talked with a designer and she suggested the following. This is a minimal change just to improve the readability. Notice that the title for each type of land received more emphasis since it's one level above the table in the content hierarchy (it's wrapped in a `<h4>` now).

![screen shot 2017-10-14 at 19 17 51](https://user-images.githubusercontent.com/958870/31579814-08506006-b115-11e7-9cd5-64e49780c602.png)
 
What do you think?

**Comment by WaveHack** [comment]
I like it 👍 Feel free to send a PR for it.

**Comment by WaveHack** [comment]
Also this designer friend of yours, would she be interested in collaborating or giving some additional feedback on some UX-related things?

I've been doing everything myself the past few years, but I'm just a developer and no designer at all. I feel like a lot of improvements could be made by just moving some HTML and CSS tags around. I'm actually looking for someone (e.g. a designer) to help me with this.

**Comment by straube** [comment]
@WaveHack I'll talk with her to ask if she has some free time to help with the project. Could she contact you on the email in your Github profile?

**Comment by WaveHack** [comment]
Thanks! Much appreciated. And yeah that's my email address I can be contacted on.
